name: Prettier
on: [push, pull_request]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:  
          ref: ${{ github.head_ref }}
      - uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,md}